### ISSUE TITLE
Prax not working on ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by khanimdad** [ysbaddaden/prax#87]
After setting it up by following the instruction from here https://github.com/ysbaddaden/prax
when i hit http://trunk.dev, http://trunk.dev/, trunk.dev, or trunk.dev/ then it does not work in any case but results in search page from my ISP.

Any idea on how can i fix it?

**Comment by adamcrown** [comment]
This is likely an unrelated issue but I thought I'd mention it here in case somebody else is having the same problem.

One day I just started having issues with prax on my Ubuntu 14.04 machine but only from Chrome. Everything else worked fine. I ran into [this thread](https://github.com/basecamp/pow/issues/397) and disabling __Built-in Asynchronous DNS__ in `chrome://flags` fixed the issue for me.

I saw the same `undefined method 'split' for nil:NilClass` that others were seeing and looking into [the code](https://github.com/ysbaddaden/prax/blob/517f98d48afd40a1936066bfe75360a2478a5cdb/lib/prax/request.rb#L73) it seemed that `header('Host')` was returning `nil`.

Not sure how Built-in Asynchronous DNS is related to a missing host header but maybe this info will be helpful for somebody else.

**Comment by emanuil-tolev** [comment]
> sounds like the Ubuntu 14.04 bug is related to iptables rules not working (PREROUTING should state 192.168.0.0/24 not 0.0.0.0/24)

Hm, I had prax working for a couple of weeks, but trying to use it now about another week later, I get Connection Refused in the browser. Ubuntu 14.04.

```
# sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

Prax itself seems to work

```
# PRAX_DEBUG=1 prax start -f
I, [2015-01-16T16:11:52.433882 #10168]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
```

But when I try to access myapp.dev:20558 or :20559 I get:

```
I, [2015-01-16T16:15:44.407916 #10168]  INFO -- : Spawning application 'myapp' [/home/emanuil/cl/myapp]
D, [2015-01-16T16:15:44.408042 #10168] DEBUG -- : ["/home/emanuil/software/prax/bin/racker", "--server", "/home/emanuil/.prax/_sockets/myapp.sock"]
D, [2015-01-16T16:15:46.101946 #10168] DEBUG -- : Application 'myapp' is ready on unix:/home/emanuil/.prax/_sockets/myapp.sock
E, [2015-01-16T16:15:54.331335 #10168] ERROR -- : NoMethodError: undefined method `split' for nil:NilClass
  /home/emanuil/software/prax/lib/prax/request.rb:73:in `host'
  /home/emanuil/software/prax/lib/prax/handler.rb:57:in `app_name'
  /home/emanuil/software/prax/lib/prax/handler.rb:17:in `handle'
  /home/emanuil/software/prax/lib/prax.rb:20:in `perform'
  /home/emanuil/software/prax/lib/prax/microworker.rb:84:in `block in work'
  /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `each'
  /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `work'
  /home/emanuil/software/prax/lib/prax/microworker.rb:63:in `block in spawn'
I, [2015-01-16T16:15:54.331406 #10168]  INFO -- : Respawning failed worker
/home/emanuil/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/urlmap.rb:53:in `+': no implicit conversion of Fixnum into String (TypeError)
        from /home/emanuil/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/urlmap.rb:53:in `block in call'
        from /home/emanuil/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
        from /home/emanuil/.rvm/gems/ruby-2.1.2/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
        from /home/emanuil/software/prax/lib/racker/handler.rb:16:in `block in handle'
        from /home/emanuil/software/prax/lib/racker/handler.rb:43:in `catch_error'
        from /home/emanuil/software/prax/lib/racker/handler.rb:16:in `handle'
        from /home/emanuil/software/prax/lib/racker.rb:16:in `perform'
        from /home/emanuil/software/prax/lib/prax/microworker.rb:84:in `block in work'
        from /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `each'
        from /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `work'
        from /home/emanuil/software/prax/lib/prax/microworker.rb:63:in `block in spawn'
D, [2015-01-16T16:15:58.357013 #10168] DEBUG -- : Killing myapp (10721)...
I, [2015-01-16T16:15:58.357279 #10168]  INFO -- : Forcing restart of myapp (/home/emanuil/cl/myapp)
I, [2015-01-16T16:15:58.357334 #10168]  INFO -- : Spawning application 'myapp' [/home/emanuil/cl/myapp]
# aaand off we go again, same error
```

Prax config:

```
# cat ~/.praxconfig
rvm_path="$HOME/.rvm/"
source "$rvm_path/scripts/rvm"
cd $PWD
```

**Comment by ysbaddaden** [comment]
I recently pushed a few commits on master to fix the split error on missing host header: #113

Please upgrade Prax and tell me if it still happens.

**Comment by emanuil-tolev** [comment]
Yep, did upgrade, still happening :(.

```sh
git pull
./bin/prax install
# restart browser
cd <myapp>
prax link
# stdout said
# rm -f '/home/emanuil/.prax/myapp'
# ln -s '/home/emanuil/cl/myapp' '/home/emanuil/.prax/myapp'
# the symlink is correct and the folder is there, so this bit is doing the right thing
prax start -f
```

But when I hit myapp.dev it never makes it to prax - I can see no lines are appearing in the log, and I get connection refused.

```
PING myapp.dev (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.039 ms
```

Iptables after prax upgrade (it said it was setting up firewall rules):
```
# sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination
```

Now, trying to connect to localhost:20558 and :20559
```
E, [2015-01-19T18:36:50.150387 #612] ERROR -- : Prax::NoSuchApp: Prax::NoSuchApp
  /home/emanuil/software/prax/lib/prax/application.rb:16:in `initialize'
  /home/emanuil/software/prax/lib/prax/spawner.rb:49:in `new'
  /home/emanuil/software/prax/lib/prax/spawner.rb:49:in `spawn'
  /home/emanuil/software/prax/lib/prax/spawner.rb:23:in `block in get'
  /home/emanuil/software/prax/lib/prax/spawner.rb:17:in `synchronize'
  /home/emanuil/software/prax/lib/prax/spawner.rb:17:in `get'
  /home/emanuil/software/prax/lib/prax/handler.rb:62:in `app'
  (erb):3:in `render_to_string'
  /home/emanuil/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/erb.rb:850:in `eval'
  /home/emanuil/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/erb.rb:850:in `result'
  /home/emanuil/software/prax/lib/prax/render.rb:24:in `render_to_string'
  /home/emanuil/software/prax/lib/prax/render.rb:9:in `render'
  /home/emanuil/software/prax/lib/prax/handler.rb:33:in `rescue in handle'
  /home/emanuil/software/prax/lib/prax/handler.rb:47:in `handle'
  /home/emanuil/software/prax/lib/prax.rb:21:in `perform'
  /home/emanuil/software/prax/lib/prax/microworker.rb:84:in `block in work'
  /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `each'
  /home/emanuil/software/prax/lib/prax/microworker.rb:77:in `work'
  /home/emanuil/software/prax/lib/prax/microworker.rb:63:in `block in spawn'
I, [2015-01-19T18:36:50.152692 #612]  INFO -- : Respawning failed worker
```

After a few connection attempts (notably perhaps after changing the port I'm accessing from 20558 to 20559 or vice versa), it seems to just hang. The browser stays in "Waiting for response". Ctrl+C-ing prax at this point gives this little piece:

```
^C/home/emanuil/software/prax/lib/prax/ssl.rb:18:in `accept': SSL_accept returned=1 errno=0 state=unknown state: http request (OpenSSL::SSL::SSLError)
        from /home/emanuil/software/prax/lib/prax/ssl.rb:18:in `accept_nonblock'
        from /home/emanuil/software/prax/lib/prax/microserver.rb:77:in `block in select'
        from /home/emanuil/software/prax/lib/prax/microserver.rb:72:in `each'
        from /home/emanuil/software/prax/lib/prax/microserver.rb:72:in `select'
        from /home/emanuil/software/prax/lib/prax/microserver.rb:31:in `block in run'
```

**Comment by emanuil-tolev** [comment]
> After a few connection attempts (notably perhaps after changing the port I'm accessing from 20558 to 20559 or vice versa), it seems to just hang

Actually the hanging and SSL error on exit seem to happen as soon as I access 20558. 20559 returns No data received in the browser, and the NoSuchApp error that can be seen above.

**Comment by ysbaddaden** [comment]
There are a bunch of problems here.

I think the iptables rules arent working, hence no redirection :80 to :20559. Don't know why, thought.

The problem on :20559 is most certainly that prax can't find the host anywhere in your HTTP request, so yeah, the application can't be found.

Can you send the request the browser makes somewhere?

**Comment by karlwilbur** [comment]
Trying to connect to ```localhost:20558``` or ```localhost:20559``` will not work with prax. Prax expects the host name to match an application name in the format ```myapp.dev```. 

Where you ran:
```
cd <myapp>
prax link
```
Prax makes a link to the app, in this case called ```myapp```:
```
# ln -s '/home/emanuil/cl/myapp' '/home/emanuil/.prax/myapp'
```

After those steps have been done, Prax's DNS resolution and request routing will forward any requests to ```myapp.dev``` to the app that lives in ```/home/emanuil/cl/myapp```. This is not possible if you use ```localhost```.

Because you can have many apps running at the same time, Prax uses the hostname of the request for determining to which app the request should be routed. The hostname much match the liink name in ```~/.prax``` (which usually marches the name pf the app's root folder).

FWIW, I have been successfully using Prax with several rails apps on all of my Ubuntu 14.04 machines (2 desktops and 3 laptops) and so have all of my contractors. I have installed Prax several times on vanilla Ubuntu 14.04 machines with total success (I don't use SSL as much as I expected so I am not as certain about SSL, but I seem to recall that it works fine too once you get past the security warning).

Here's my output from iptables:
```
karl@karl-S500CA [16:11:27] [~] 
-> % sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination   
```

@emanuil-tolev, I noticed that in your PREROUTING table, you have duplicate entries. I don't think this would be a problem, but it might be. Try stopping the prax "service" to remove the iptables entries then restart to reapply. Does that change anything for you?

Here is what I mean:
```
karl@karl-S500CA [16:15:29] [~] 
-> % sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
karl@karl-S500CA [16:15:31] [~] 
-> % sudo service prax stop    
karl@karl-S500CA [16:15:34] [~] 
-> % sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
karl@karl-S500CA [16:15:35] [~] 
-> % sudo service prax start   
karl@karl-S500CA [16:15:38] [~] 
-> % sudo iptables -t nat -L -n
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
karl@karl-S500CA [16:15:39] [~] 
-> % 
```

**Comment by karlwilbur** [comment]
@emanuil-tolev,

Also, try running ```rails c``` and/or ```rails s``` in your app's root. I have had several instances where my app failed to start because of something in the app (some stupid thing that I did in the app) and it was hidden from me because it never appeared in the prax log. Using ```rails s``` will sometime make the issue very obvious.

**Comment by khanimdad** [comment]
Now my app is running on http://unicircles.dev:3000, but the problem is that 
a) I do not  want port number here (Not sure how to avoid it)
b) I still need to keep app server running (ie "rails server" )

Any idea on how to fix a and b above?

**Comment by karlwilbur** [comment]
Don't run "rails server". Just connect to http://unicircles.dev/ (without the port).

Make sure that you have run both of these in your terminal:
```
sudo service prax start
```
and 
```
prax start
```

**Comment by zeitnot** [comment]
@karlwilbur I have the same problem with @khanimdad. Without port number and `rails s` it does not work. After `$ prax start` I run `$ sudo iptables -t nat -L -n` and that gives the following output.

```shell
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
RETURN     all  --  192.168.122.0/24     224.0.0.0/24        
RETURN     all  --  192.168.122.0/24     255.255.255.255     
MASQUERADE  tcp  --  192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
MASQUERADE  udp  --  192.168.122.0/24    !192.168.122.0/24     masq ports: 1024-65535
MASQUERADE  all  --  192.168.122.0/24    !192.168.122.0/24    
MASQUERADE  all  --  10.0.3.0/24         !10.0.3.0/24
```

**Comment by karlwilbur** [comment]
@zeitnot You need to have run ```prax link``` link in your project directory. Here is a complete example on Ubuntu 14.04 with Rbenv installed:

```
git clone https://github.com/ysbaddaden/prax.git /opt/prax
cd /opt/prax/ && sudo ./bin/prax install
sudo prax start
cd ~/Projects/ExampleApp/
git clone git@git.kandrsoftware.com:exampleapp.git
cd exampleapp
prax link
git checkout develop
rbenv install `cat .ruby-version`
bundle install
cp config/settings.local{.example,}.yml
rake db:create && rake db:migrate && rake db:seed
prax stop && prax start
google-chrome http://exampleapp.dev/
```

I also highly recommend Ubuntu Wart Removal (https://github.com/ab/ubuntu-wart-removal). Particularly ```disable-dnsmasq.sh```. That might be your problem.

Here's the output of my ```sudo iptables -t nat -L -n```:
```
karl@karl-S500CA [16:46:00] [~/Projects/ExampleApp/exampleapp] [master *]
-> % sudo iptables -t nat -L -n
[sudo] password for karl: 
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination  
```

**Comment by karlwilbur** [comment]
This might help with troubleshooting...
Tail the prax logs. To do this run:
```
tail -fn0 ~/.prax/_logs/prax.log ~/.prax/_logs/exampleapp.log 
```

Here is that run on my machine:
```
karl@karl-S500CA [17:00:13] [~/Projects/ExampleApp/exampleapp] [master *]
-> % tail -fn0 ~/.prax/_logs/prax.log ~/.prax/_logs/exampleapp.log 
==> /home/karl/.prax/_logs/prax.log <==

==> /home/karl/.prax/_logs/exampleapp.log <==

``` 

Then in a new tab, run:
```
prax stop && prax start && google-chrome http://exampleapp.dev/
```

Here is my tail output:
```
karl@karl-S500CA [17:00:13] [~/Projects/ExampleApp/exampleapp] [master *]
-> % tail -fn0 ~/.prax/_logs/prax.log ~/.prax/_logs/exampleapp.log 
==> /home/karl/.prax/_logs/prax.log <==

==> /home/karl/.prax/_logs/exampleapp.log <==

==> /home/karl/.prax/_logs/prax.log <==
I, [2015-02-07T17:00:33.473679 #31758]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
I, [2015-02-07T17:00:51.892546 #31758]  INFO -- : Spawning application 'exampleapp' [/home/karl/Projects/ExampleApp/exampleapp]

==> /home/karl/.prax/_logs/exampleapp.log <==
bundle exec ruby /opt/prax/bin/../lib/racker/command.rb --server /home/karl/.prax/_sockets/exampleapp.sock
I, [2015-02-07T17:00:53.191679 #31856]  INFO -- : Racker is ready to receive connections on /home/karl/.prax/_sockets/exampleapp.sock.

```

**Comment by khanimdad** [comment]
@karlwilbur , sorry still not working, i did what you asked for eg stopped rails server then 
sudo service prax start
and
prax start

http://unicircles.dev 
 returns This webpage is not available

**Comment by karlwilbur** [comment]
@khanimdad, did you tail the logs? Please post the last few lines of both the prax log and the app log.

Also, try ```prax stop``` then ```prax start```.

**Comment by khanimdad** [comment]
@karlwilbur , here is my prax log file, but app log file is empty.

imdad@Youtoo:~/Youtoo/devold$ tail -n 20 -f ~/.prax/_logs/prax.log
I, [2015-02-07T17:22:46.976814 #10960]  INFO -- : Forcing restart of unicircles (/home/imdad/Youtoo/devold)
I, [2015-02-07T17:22:46.978613 #10960]  INFO -- : Spawning application 'unicircles' [/home/imdad/Youtoo/devold]
E, [2015-02-07T17:22:52.850751 #10960] ERROR -- : ArgumentError: bad argument (expected URI object or URI string)
  /home/imdad/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/uri/common.rb:996:in `URI'
  /opt/prax/lib/prax/request.rb:136:in `determine_host'
  /opt/prax/lib/prax/request.rb:75:in `host'
  /opt/prax/lib/prax/handler.rb:66:in `app_name'
  /opt/prax/lib/prax/handler.rb:17:in `handle'
  /opt/prax/lib/prax.rb:21:in `perform'
  /opt/prax/lib/prax/microworker.rb:84:in `block in work'
  /opt/prax/lib/prax/microworker.rb:77:in `each'
  /opt/prax/lib/prax/microworker.rb:77:in `work'
  /opt/prax/lib/prax/microworker.rb:63:in `block in spawn'
I, [2015-02-07T17:22:52.850942 #10960]  INFO -- : Respawning failed worker
I, [2015-02-07T17:23:17.086217 #10960]  INFO -- : Forcing restart of unicircles (/home/imdad/Youtoo/devold)
I, [2015-02-07T17:23:17.086380 #10960]  INFO -- : Spawning application 'unicircles' [/home/imdad/Youtoo/devold]
I, [2015-02-07T17:33:30.285394 #10960]  INFO -- : Killing unicircles: expired TTL
I, [2015-02-08T09:31:27.529681 #14942]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
I, [2015-02-08T10:03:29.787563 #4348]  INFO -- : Prax is ready to receive connections on :20559 and :20558.
I, [2015-02-08T12:14:40.867720 #8023]  INFO -- : Prax is ready to receive connections on :20559 and :20558.

**Comment by ysbaddaden** [comment]
Prax fails because it can't find the Host in your request. Either the Host header is missing or it's not provided in the URI or something.

It happens sometimes but I have no idea what's going on. I can't replicate and never got dumped requests to understand what's going on :-(

See #113 and #112

**Comment by karlwilbur** [comment]
@khanimdad, Please post the output from:
```
curl -vi http://unicircles.dev/
```

**Comment by zeitnot** [comment]
@karlwilbur I have done already what have you said before but the result is same with @khanimdad's. I did run `disable-dnsmasq.sh` as well which you mentioned.

**Comment by karlwilbur** [comment]
@zeitnot, can you also do the steps I mentioned above and show me the output from your log file, as well as the output from the curl command above?

**Comment by khanimdad** [comment]
@karlwilbur , on "curl -vi http://unicircles.dev/" i get below...
imdad@Youtoo:~/Hailisys/mymster/new$ curl -vi http://unicircles.dev/
* Hostname was NOT found in DNS cache
*   Trying 127.0.53.53...
* connect to 127.0.53.53 port 80 failed: Connection refused
* Failed to connect to unicircles.dev port 80: Connection refused
* Closing connection 0
curl: (7) Failed to connect to unicircles.dev port 80: Connection refused

**Comment by ysbaddaden** [comment]
`127.0.53.53`? There is something wrong. Either in prax nss resolver, or there is a DNS server resolving .dev domains to this weird IP. It should always resolve .dev to 127.0.0.1 and/or ::1.

Note: you may want to disable the nss extention, and configure dnsmasq to resolve .dev domains instead. It may prove better.

Note: I never had to disable the dnsmasq that Ubuntu installs and runs by default. I had problems with OpenDNS resolving unknown domains —but that can be configured.

**Comment by khanimdad** [comment]
@ysbaddaden , can you explain how can i solve this issue?

**Comment by ysbaddaden** [comment]
Depends where the problem comes. You may use `getent hosts unicircles.dev` on the command line, to verify what dev domains are being resolved to —don't use `host` and `dig`, they directly ask DNS servers and bypass NSSswitch. Actually, if `host unicircles.dev` resolves to something, your problem is a DNS server somewhere. Maybe dnsmasq, or `/etc/hosts` or the DNS of your Internet Provider or something else Ubuntu installed.

**Comment by zeitnot** [comment]
@karlwilbur 
```shell
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to athena.dev (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: athena.dev
> Accept: */*
>
```

BTW, there is no any log under `~/.prax` folder.

**Comment by NomNomCameron** [comment]
I seem to be having the same problem on Ubuntu 14.04, any request to `http://myapp.dev` doesn't make it to prax. Any word on this?

**Comment by karlwilbur** [comment]
@NomNomCameron,

Make sure you don't have another web server running (like Apache or Nginx). 

Is ```iptables``` set up correctly?
```
sudo iptables -t nat -L -n
```

Is name resolution working for you?
```
ping -c 1 rapidreels.dev
```

What do you get from curl?
```
curl -vi http://myapp.dev/
```

Earlier tonight I was working with a developer who was getting Prax running for the first on their Ubuntu 14.04 machine. Chrome was caching the "No data received" page and refused to show anything else. Firefox, Chromium, Lynx, wget, and cURL all worked fine though. So, apparently Google Chrome has some caching issues.

**Comment by NomNomCameron** [comment]
I do have nginx installed but it isn't running

`sudo iptables -t nat -L -n`

```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 redir ports 20558

Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 20559
REDIRECT   tcp  --  0.0.0.0/0            127.0.0.1            tcp dpt:443 redir ports 20558

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination         
```

`ping -c 1 myapp.dev`

```
PING myapp.dev (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_seq=1 ttl=64 time=0.023 ms

--- myapp.dev ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.023/0.023/0.023/0.000 ms
```

`curl -vi http://myapp.dev`

```
* Rebuilt URL to: myapp.dev/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 80 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to myapp.dev (127.0.0.1) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.35.0
> Host: myapp.dev
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host myapp.dev left intact
curl: (52) Empty reply from server
```

**Comment by karlwilbur** [comment]
@NomNomCameron, 

All that looks good. Does your app start correctly with `rails c`? If so, does it work when you run `rails s` and connect on `http://localhost:3000/`?

If both of those are working, let's see the output of your logs. This will start monitoring new log entries:
```
tail -fn0 ~/.prax/_logs/{prax,myapp}.log
```

then run:
```
prax stop; prax start; curl -vi http://myapp.dev;
```
Then post what prax is saying.

**Comment by ysbaddaden** [comment]
Note that myapp.dev is a placeholder name. If your app is named foobar, access foobar.dev instaed, etc.

**Comment by NomNomCameron** [comment]
I wanted to uninstall prax and start from scratch, trying to use the uninstall script in libexec I get:

```
Stopping prax
./prax-uninstall: line 13: cd: /ext: No such file or directory
```

**Comment by karlwilbur** [comment]
```
prax stop;
sudo service prax stop;
sudo rm -rf /opt/prax /usr/local/bin/prax ~/.prax 
sudo sed -i -r -e '/\bprax\b//' /etc/nsswitch.conf
sudo update-rc.d prax remove
```

Then reinstall.

**Comment by karlwilbur** [comment]
FYI, I just ran into an issue with Prax+Chrome. Chrome is completely refusing to work correctly. All other browsers are working just fine. In trying to trouble shoot this, I came full-circle to back this thread. The most above (https://github.com/ysbaddaden/prax/issues/87#issuecomment-68762291 from @adamcrown) mentions an issue with Chrome's "Built-in Asynchronous DNS". I am not finding anything in `chrome://flags` about "Built-in Asynchronous DNS". So, while this seems to be the *exact* problem with Chrome, there doesn't seem to be a solution. This flag has been removed from Chrome and now there is no possibility of disabling it (https://chromium.googlesource.com/chromium/src/+/eabf1f5baba38d46921acd6edda594f942f7d6a1).

This is a Google Chrome issue. Google Chrome is broken (at least Version 41.0.2272.76 (64-bit)). Prax still works exactly as expected in Firefox, Lynx, cURL, Epiphay, Konqueror, or any other HTTP client that actually works.

**Comment by ysbaddaden** [comment]
Yes, async DNS *is* the problem in Chrome. I don't know why, unless they bypass NSSwitch altogether and hit DNS servers directly (WTH Google). There is still the "--disable-async-dns" flag for the time being, but that will eventually fail, too. I have no idea how we can fix that.

Could you move the discussion to it's own thread?

**Comment by ysbaddaden** [comment]
Closing since the thread went very dar, and Prax is indeed working correctly on Ubuntu 14.04

**Comment by dimonge** [comment]
The thread messages were helpful. Thanks. @khanimdad
